### ISSUE TITLE
Crush on Samsung Tab A9+ 5G

### ISSUE THREAD

**Issue by AngeloAscione** [hms-douglas/kapture#1]
Hi, i recently compiled and installed the application on a Samsung Tab A9+ 5G with  Android 14 - One UI 6.1 - Security Patch 1/Oct/2024 - Build UP1A.231005.007.
After launching the application, it asks for permissions and I grant them correctly. When trying to register the screen everything goes good until I try to stop the recording, when stopping,  the application crushes, I tried to read the logcat and this is the exception, I am not able to fix it, any ideas?

![image](https://github.com/user-attachments/assets/c2648958-7b6f-4d44-8426-12b02b90810d)

**Comment by hms-douglas** [comment]
Hello, I ran some quick tests with the model on Samsung RTL...

It seems that the device original resolution is not supported by, either (or both) the MediaRecorder or the VirtualDisplay... (Again  quick test, didn't do much research)

For now 2 solutions: 
- 1) You select a specific resolution in the app settings (e.g. 1080p);
- 2) As you built from the code instead of installing the apk, you can set a specific resolution inside the code (e.g. 1920 1080, or try one that fits better _and works_).

I'll add to my todo list to check/validate the supported resolutions inside the code in a future update...

**Comment by AngeloAscione** [comment]
That worked, thanks a lot! Wish you the best, bye!
